"""OpenMathInstruct-2 environment for Reliquary verifiable inference.

Loads Nvidia's OpenMathInstruct-2 dataset (14M math problems) generated by
Llama-3.1-405B from MATH + GSM8K. Pre-extracted ``expected_answer`` makes
reward computation more reliable than raw \\boxed{} parsing.

Disk-efficient strategy: only downloads the first N shards by default
(NVIDIA splits the dataset into 32 parquet shards of ~440k problems each;
2 shards = ~880k problems = >100x the per-window cooldown space).

Usage:
    env = OpenMathInstructEnvironment()
    p = env.get_problem(42)
    # {"prompt": "...", "ground_truth": "45", "id": "abc1234..."}
    reward = env.compute_reward(p, "the answer is \\boxed{45}")  # → 1.0
"""

from __future__ import annotations

import hashlib
import os
import re
from typing import ClassVar, Optional


# ---------------------------------------------------------------------------
# Answer extraction — reuse the balanced-brace parser from MATH env
# ---------------------------------------------------------------------------

def _last_boxed_only_string(text: str) -> Optional[str]:
    """Return the last \\boxed{...} / \\fbox{...} substring or None.

    Balanced-brace walk to handle nested expressions correctly.
    """
    idx = max(text.rfind("\\boxed{"), text.rfind("\\fbox{"))
    if idx < 0:
        return None
    try:
        open_idx = text.index("{", idx)
    except ValueError:
        return None
    depth = 0
    for j in range(open_idx, len(text)):
        c = text[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[idx : j + 1]
    return None


def _strip_boxed_wrapper(s: str) -> str:
    for prefix in (r"\boxed{", r"\fbox{"):
        if s.startswith(prefix) and s.endswith("}"):
            return s[len(prefix) : -1]
    return s


# ---------------------------------------------------------------------------
# Answer normalization — handles both LaTeX and plain numeric forms.
# OpenMathInstruct expected_answer is typically plain (e.g. "45", "3/4",
# "-2", "\\frac{1}{2}") so we accept both shapes.
# ---------------------------------------------------------------------------

_TEXT_RE = re.compile(r"\\text\{([^}]*)\}")
_MBOX_RE = re.compile(r"\\mbox\{([^}]*)\}")


def _normalize_answer(s: str) -> str:
    if s is None:
        return ""
    s = str(s)
    # Drop LaTeX spacing macros first
    for macro in (r"\!", r"\,", r"\ ", r"\;", r"\:"):
        s = s.replace(macro, "")
    s = s.replace(r"\left", "").replace(r"\right", "")
    s = s.replace(r"\dfrac", r"\frac").replace(r"\tfrac", r"\frac")
    s = _TEXT_RE.sub(r"\1", s)
    s = _MBOX_RE.sub(r"\1", s)
    s = s.replace(r"\$", "").replace("$", "")
    # Plain-number normalization (OMI specific): "3.0" -> "3", "+5" -> "5"
    s = s.strip().rstrip(".").strip()
    s = re.sub(r"\s+", "", s)
    # Strip leading + on integers
    if len(s) > 1 and s[0] == "+":
        s = s[1:]
    # "3.0" -> "3" only when there's nothing else
    if re.fullmatch(r"-?\d+\.0+", s):
        s = s.split(".", 1)[0]
    return s


# ---------------------------------------------------------------------------
# Reward
# ---------------------------------------------------------------------------

def _compute_omi_reward(problem: dict, completion: str) -> float:
    """Score an OMI completion.

    1.0 if the last \\boxed{...} normalized matches expected_answer normalized.
    0.0 otherwise. Never raises.
    """
    try:
        boxed = _last_boxed_only_string(completion)
        if boxed is None:
            # Fallback: try to find a trailing number / fraction at end of text
            # (some models output the answer without boxing)
            tail = completion.strip().split("\n")[-1].strip()
            # Match a leading number/fraction at start of last line
            m = re.match(r"^([\-\+]?\d+(?:\.\d+)?(?:/\d+)?)", tail)
            if m is None:
                return 0.0
            candidate = _normalize_answer(m.group(1))
        else:
            candidate = _normalize_answer(_strip_boxed_wrapper(boxed))
        gt = _normalize_answer(problem.get("ground_truth", ""))
        if gt == "":
            return 0.0
        return 1.0 if candidate == gt else 0.0
    except Exception:
        return 0.0


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

class OpenMathInstructEnvironment:
    """Nvidia OpenMathInstruct-2: 14M synthetic math problems.

    Deterministic ``get_problem(idx)`` wraps modulo dataset length. The
    dataset is loaded once per process (HF caches under ~/.cache/huggingface).

    Disk strategy: ``RELIQUARY_OMI_SHARDS=N`` env var controls how many of
    the 32 parquet shards to download (default: 2 = ~880k problems, ~1GB).
    Each shard is ~440k problems / ~500MB. Increase if disk allows.
    """

    name: str = "openmathinstruct"

    _dataset_cache: ClassVar[Optional[object]] = None
    _DEFAULT_SHARDS: ClassVar[int] = 2

    def __init__(self) -> None:
        if OpenMathInstructEnvironment._dataset_cache is None:
            import datasets as hf
            n_shards = int(os.environ.get("RELIQUARY_OMI_SHARDS", str(self._DEFAULT_SHARDS)))
            n_shards = max(1, min(n_shards, 32))
            # Load only the first N shards by passing explicit data_files
            # verification_mode="no_checks" skips the metadata-mandated config
            # split set ({train_1M, train_2M, train_5M}) so we can pull
            # arbitrary parquet shards directly.
            data_files = [
                f"data/train-{i:05d}-of-00032.parquet" for i in range(n_shards)
            ]
            OpenMathInstructEnvironment._dataset_cache = hf.load_dataset(
                "nvidia/OpenMathInstruct-2",
                data_files=data_files,
                split="train",
                verification_mode="no_checks",
            )
        self._dataset = OpenMathInstructEnvironment._dataset_cache

    def __len__(self) -> int:
        return len(self._dataset)

    def get_problem(self, index: int) -> dict:
        """Deterministic lookup with modulo wrap.

        Note: dataset row order is fixed by parquet file order, so the same
        ``index`` always returns the same problem across miners that loaded
        the same shard set.
        """
        idx = index % len(self._dataset)
        row = self._dataset[idx]
        question: str = row["problem"]
        expected: str = str(row.get("expected_answer", ""))
        problem_id = hashlib.sha256(question.encode()).hexdigest()[:16]
        return {
            "prompt": question,
            "ground_truth": expected,
            "id": problem_id,
        }

    def compute_reward(self, problem: dict, completion: str) -> float:
        return _compute_omi_reward(problem, completion)
